// Writes the railway layout the Blender build reads (models/railway-layout.json): the centreline sampled every metre
// with its deck height, half-width and track offset, the girder spans and the Loopline Bridge's piers, computed by
// src/world/railline.js against the street graph (loaded through Vite, so it is exactly what the game computes).
// Usage: node tools/railway-layout.mjs [--print]   (then: blender -b --factory-startup -P tools/blender/build_loopline.py)
import { createServer } from 'vite';
import fs from 'node:fs';

const server = await createServer({ server: { middlewareMode: true }, appType: 'custom', logLevel: 'error' });
try {
  const R = await server.ssrLoadModule('/src/world/railline.js');
  const r2 = (v) => Math.round(v * 100) / 100;
  const samples = [];
  for (let s = 0; s <= R.LENGTH; s += 1) {
    const p = R.at(s);
    samples.push([r2(s), r2(p.x), r2(p.z), r2(R.deckAt(s)), r2(R.halfAt(s)), r2(R.trackAt(s))]);
  }
  const out = {
    about: 'Generated by tools/railway-layout.mjs from src/world/railline.js: do not edit. samples: [s, x, z, deck, half, track].',
    length: r2(R.LENGTH), deck: R.DECK, platform: R.PLATFORM,
    spans: R.spans.map((sp) => ({ s0: r2(sp.s0), s1: r2(sp.s1), style: sp.style, hero: !!sp.hero, over: sp.over, cols: sp.cols.map(([s, side]) => [r2(s), side]) })),
    piers: R.looplinePiers().map((p) => ({ s: r2(p.s), water: p.water })),
    stations: R.stations.map((st) => ({ name: st.name, s: r2(st.s), len: st.len, dressed: st.dressed, canopy: st.canopy })),
    gcd: R.GCD, lansdowne: R.LANSDOWNE, loop: R.LOOP,
    samples,
  };
  fs.mkdirSync('models', { recursive: true });
  fs.writeFileSync('models/railway-layout.json', JSON.stringify(out));
  console.log(`length ${out.length} m, ${out.spans.length} spans, ${out.piers.length} piers -> models/railway-layout.json`);
  if (process.argv.includes('--print')) {
    for (const sp of out.spans) { const a = R.at(sp.s0), b = R.at(sp.s1); console.log(`span ${sp.s0}-${sp.s1} (${(sp.s1 - sp.s0).toFixed(1)} m) ${sp.style}${sp.hero ? ' HERO' : ''} [${sp.over.join(', ')}] cols ${sp.cols.map((c) => c.join(":")).join(" ")} (${a.x.toFixed(0)},${a.z.toFixed(0)})->(${b.x.toFixed(0)},${b.z.toFixed(0)})`); }
    for (const st of out.stations) { const p = R.at(st.s); console.log(`station ${st.name} s=${st.s} (${p.x.toFixed(0)},${p.z.toFixed(0)}) deck ${R.deckAt(st.s).toFixed(2)}`); }
    console.log('piers', JSON.stringify(out.piers), 'gcd', JSON.stringify(R.GCD), 'lansdowne', JSON.stringify(R.LANSDOWNE), 'loop', JSON.stringify(R.LOOP));
  }
} finally {
  await server.close();
}
